msrv="1.83.0"
absolute-paths-max-segments=3
cargo-ignore-publish=true
allow-dbg-in-tests=true
allow-expect-in-tests=true
allow-panic-in-tests=true
allow-print-in-tests=true
allowed-duplicate-crates=[
    "ahash",
    "syn",
    "hashbrown",
]