services:
  server-dedicated-machine:
    image: debian:latest
    container_name: kageshirei-server-dedicated-machine
    entrypoint: /app/target/kageshirei-server
    command:
      - run
      - -c
      - /app/server/sample-config.json
    volumes:
      - ".:/app"

  # Development/testing database
  postgres:
    image: postgres:latest
    container_name: kageshirei-postgres
    restart: always
    environment:
      # Change these to your liking
      POSTGRES_PASSWORD: kageshirei
      POSTGRES_DB: kageshirei
      POSTGRES_USER: kageshirei
    ports:
      - "5432:5432"