version: '3.8'

services:
  server-dedicated-machine:
    image: debian:bookworm
    container_name: kageshirei-server-dedicated-machine
    entrypoint: /bin/bash
    command:
      - -c
      - "apt-get update && apt-get install -y libssl3 && /app/target/debug/kageshirei-server run -c /app/server/sample-config.json"
    volumes:
      - ".:/app"
    depends_on:
      - postgres
    environment:
      - POSTGRES_PASSWORD=kageshirei
      - POSTGRES_DB=kageshirei
      - POSTGRES_USER=kageshirei
    ports:
      - "8080:8080"  # 修改为不同的端口

  # Development/testing database
  postgres:
    image: postgres:latest
    container_name: kageshirei-postgres
    restart: always
    environment:
      # Change these to your liking
      POSTGRES_PASSWORD: kageshirei
      POSTGRES_DB: kageshirei
      POSTGRES_USER: kageshirei
    ports:
      - "5432:5432"
