[config]
skip_core_tasks = true
default_to_workspace = false

[env]
# Force the child makefiles to extend this workspace (root) makefile
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "libs/*"

[env.development]
# Define the default target to build
BUILD_MODE = ""

[env.release]
# Define the default target to build
BUILD_MODE = "--release"

# Define the default task to run
[tasks.default]
description = "Build all the targets in parallel"
alias = "all"

# Run all tasks in parallel
[tasks.all]
description = "Build all the targets in parallel"
dependencies = [
    "setup-env",
]
run_task = { parallel = true, name = [
    "build-agent",
    "build-coffee-ldr",
    "build-server",
] }

# Define the tasks responsible for setting up the environment for the build
[tasks.setup-env.linux]
rustup target add <missing-target>
description = "Setup the environment for the build"
install_script = '''
    rustup target add x86_64-unknown-linux-gnu --force-non-host
    rustup target add x86_64-pc-windows-gnu --force-non-host
    rustup target add i686-pc-windows-gnu --force-non-host
    rustup toolchain add nightly-i686-pc-windows-gnu
    rustup toolchain add nightly-x86_64-pc-windows-gnu
    rustup toolchain add nightly-x86_64-unknown-linux-gnu
'''

# Define the tasks responsible for setting up the environment for the build
[tasks.setup-env.windows]
description = "Setup the environment for the build"
install_script = '''
    rustup target add x86_64-unknown-linux-gnu --force-non-host
    rustup target add x86_64-pc-windows-msvc --force-non-host
    rustup target add i686-pc-windows-msvc --force-non-host
    rustup toolchain add nightly-i686-pc-windows-msvc
    rustup toolchain add nightly-x86_64-pc-windows-msvc
    rustup toolchain add nightly-x86_64-unknown-linux-gnu
'''

# Define the tasks responsible for building the agent (linux and windows)
[tasks.build-agent]
clear = true
description = "Build the agent from linux (x86 and x64)"
env = { CARGO_MAKE_WORKSPACE_EMULATION = true, CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = "agent" }
run_task = { name = "build-agent-task", fork = true }

# Define the tasks responsible for buildind coffee-ldr (linux and windows)
[tasks.build-coffee-ldr.linux]
clear = true
description = "Build the coffee-ldr from linux (x86 and x64)"
env = { TARGET = "-pc-windows-gnu" }
run_task = "build-coffee-common"

[tasks.build-coffee-ldr.windows]
clear = true
description = "Build the coffee-ldr from linux (x86 and x64)"
env = { TARGET = "-pc-windows-msvc" }
run_task = "build-coffee-common"

[tasks.build-coffee-common]
clear = true
description = "Build the coffee-ldr from windows (x86 and x64)"
script_runner = "@shell"
script = '''
echo "\$ cargo +nightly build ${BUILD_MODE} --target x86_64${TARGET} --bin coffee-ldr"
cargo +nightly build ${BUILD_MODE} --target x86_64${TARGET} --bin coffee-ldr
echo "\$ cargo +nightly build ${BUILD_MODE} --target i686${TARGET} --bin coffee-ldr"
cargo +nightly build ${BUILD_MODE} --target i686${TARGET} --bin coffee-ldr
'''

# Define the tasks responsible for building the server (linux and windows)
[tasks.build-server.linux]
clear = true
description = "Build the server from linux, for linux"
script_runner = "@shell"
script = '''
echo "\$ cargo +nightly build ${BUILD_MODE} --target x86_64-unknown-linux-gnu --bin kageshirei-server"
cargo +nightly build ${BUILD_MODE} --target x86_64-unknown-linux-gnu --bin kageshirei-server
'''

# Define the tasks responsible for building the server (linux and windows)
[tasks.build-server.windows]
clear = true
description = "Build the server from windows, for windows"
script_runner = "@shell"
script = "powershell ./scripts/cargo-make-build.ps1"
