[package]
name = "mod-agentcore"
version = "0.1.0"
edition = "2021"

[dependencies]
mod-hhtgates = {path = "../../modules/mod-hhtgates"}
kageshirei-win32 = {path = "../../libs/kageshirei-win32" }
spin = "0.9"


[dev-dependencies]
libc-print = "0.1.23"
