[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.default]
clear = true
alias = "build"

[tasks.build]
script_runner = "@shell"
script = '''
rustup target add wasm32-unknown-unknown
cargo build --release --target wasm32-unknown-unknown
'''