[package]
name = "rs2-server"

[profile.release]
strip = true
opt-level = 3
incremental = true
debug-assertions = false
lto = true

[dependencies]
# Command line parsing and advanced error handling
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
# Non async logging
log = { version = "0.4.21" }
fern = { version = "0.6.2", features = ["colored"] }
# Misc
humantime = "2.1.0"
colored = "2.1.0"
# Unix related features, used by the compiler
nix = { version = "0.28.0", features = ["user"] }

[features]
