[package]
name = "srv-mod-operator-api"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.18.1", features = ["derive"] }
tokio = { version = "1.0", features = ["full", "tracing", "test-util"] }
tokio-util = { version = "0.7.11", features = ["full"] }
once_cell = "1.19.0"
axum = { version = "0.7.5", features = ["http2", "multipart", "macros"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
tower = { version = "0.4.4" }
tower-http = { version = "0.5.2", features = ["catch-panic", "normalize-path", "sensitive-headers", "trace", "validate-request", "compression-full", "limit"] }
tracing = "0.1"
jsonwebtoken = "9.3.0"
rs2-utils = { path = "../../libs/rs2-utils" }
rs2-crypt = { path = "../../libs/rs2-crypt", features = ["argon2"] }
chrono = "0.4.38"
srv-mod-config = { path = "../srv-mod-config" }
srv-mod-database = { path = "../srv-mod-database" }
humantime = "2.1.0"