[package]
name = "srv-mod-operator-api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
validator = { version = "0.18.1", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full", "tracing", "test-util"] }
tokio-util = { version = "0.7.12", features = ["full"] }
once_cell = "1.20.2"
axum = { version = "0.7.7", features = ["http2", "multipart", "macros"] }
axum-extra = { version = "0.9.4", features = ["typed-header"] }
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
tower = { version = "0.5.1" }
tower-http = { version = "0.6.1", features = [
    "catch-panic",
    "normalize-path",
    "sensitive-headers",
    "trace",
    "validate-request",
    "compression-full",
    "limit",
    "cors"
] }
tracing = "0.1.40"
jsonwebtoken = "9.3.0"
rs2-utils = { path = "../../libs/rs2-utils" }
rs2-crypt = { path = "../../libs/rs2-crypt", features = ["argon2"] }
chrono = "0.4.38"
srv-mod-config = { path = "../srv-mod-config" }
humantime = "2.1.0"
srv-mod-terminal-emulator-commands = { path = "../srv-mod-terminal-emulator-commands" }
futures = "0.3.31"
futures-util = "0.3.31"
tokio-stream = { version = "0.1.16", features = ["sync"] }
srv-mod-entity = { path = "../srv-mod-entity" }