[package]
name = "mod-protocol-json"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
debug = false
debug-assertions = false
panic = "abort"
incremental = false

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
kageshirei-communication-protocol = { path = "../../libs/kageshirei-communication-protocol" }
kageshirei-crypt = { path = "../../libs/kageshirei-crypt" }
reqwest = { version = "0.12.8", features = ["rustls-tls", "stream"] }
bytes = "1.7.2"

[dev-dependencies]
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.7"
tokio-util = "0.7.12"

[lints]
workspace = true