[package]
name = "mod-protocol-json"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
debug = false
debug-assertions = false
panic = "abort"
incremental = false

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
serde_json = { version = "1.0.117" }
rs2-communication-protocol = { path = "../../libs/rs2-communication-protocol" }
rs2-crypt = { path = "../../libs/rs2-crypt" }
reqwest = { version = "0.12.4", features = ["rustls-tls", "stream"] }
bytes = "1.6.0"
uuid = { version = "1.8.0", features = ["v4"] }
anyhow = "1.0.86"

[dev-dependencies]
tokio = { version = "1.37.0", features = ["full"] }
axum = "0.7.5"
tokio-util = "0.7.11"