[package]
name = "mod-protocol-json"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
debug = false
debug-assertions = false
panic = "abort"
incremental = false

[dependencies]
serde = { version = "1.0.202", features = ["derive"] }
serde_json = { version = "1.0.117" }