//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::{entity::prelude::*, sqlx::types::chrono::Utc, ActiveValue::Set};
use serde::{Deserialize, Serialize};

use crate::helpers::CUID2;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "terminal_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id:               String,
    pub ran_by:           String,
    #[sea_orm(column_type = "Text")]
    pub command:          String,
    pub session_id:       Option<String>,
    pub is_global:        bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub output:           Option<String>,
    pub exit_code:        Option<i32>,
    pub sequence_counter: i64,
    pub deleted_at:       Option<DateTime>,
    pub restored_at:      Option<DateTime>,
    pub created_at:       DateTime,
    pub updated_at:       DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agent::Entity",
        from = "Column::SessionId",
        to = "super::agent::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Agent,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::RanBy",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::agent::Entity> for Entity {
    fn to() -> RelationDef { Relation::Agent.def() }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef { Relation::User.def() }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            // Generate a new unique ID
            id: Set(CUID2.create_id()),
            ..ActiveModelTrait::default()
        }
    }

    async fn before_save<C>(self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        // Clone the model to avoid moving it
        let mut model = self;

        if insert {
            // Update the `created_at` field with the current time
            model.created_at = Set(Utc::now().naive_utc());
        }

        // Update the `updated_at` field with the current time
        model.updated_at = Set(Utc::now().naive_utc());
        Ok(model)
    }
}
