[package]
name = "srv-mod-config"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.21" }
tokio = { version = "1.0", features = ["full", "tracing", "test-util"] }
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.18.1", features = ["derive"] }
rs2-utils = { path = "../../libs/rs2-utils", features = ["print-validation-error"] }
anyhow = "1.0.86"
serde_json = "1.0.117"
nix = "0.29.0"
once_cell = "1.19.0"
regex = "1.10.4"