[package]
name = "srv-mod-config"
version = "0.1.0"
edition = "2021"
categories = ["simulation"]
keywords = ["kageshirei", "server", "module", "configuration"]
repository = "https://github.com/Kageshirei/KageShirei"
license-file = "../../LICENSE"
description = "A module for the KageShirei server that provides the shared server configurations."
readme = "README.md"

[dependencies]
log = { version = "0.4.22" }
tokio = { version = "1.40.0", features = ["full", "tracing", "test-util"] }
serde = { version = "1.0.210", features = ["derive"] }
validator = { version = "0.18.1", features = ["derive"] }
kageshirei-utils = { path = "../../libs/kageshirei-utils" }
serde_json = "1.0.128"
nix = { version = "0.29.0", features = ["user"] }
once_cell = "1.20.2"
regex = "1.11.0"
winapi = { version = "0.3.9", features = ["processthreadsapi", "securitybaseapi", "winnt", "handleapi", "minwindef"] }
kageshirei-extensions = { path = "../../libs/kageshirei-extensions" }

[lints]
workspace = true