[package]
name = "mod-tokio-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
kageshirei-runtime = { path = "../../libs/kageshirei-runtime" }
kageshirei-communication-protocol = { path = "../../libs/kageshirei-communication-protocol" }
tokio = { version = "1", features = ["full"] }