[package]
name = "mod-tokio-runtime"
version = "0.1.0"
edition = "2021"
categories = ["simulation"]
keywords = ["kageshirei", "agent", "module", "tokio", "runtime"]
repository = "https://github.com/Kageshirei/KageShirei"
license-file = "../../LICENSE"
description = "A module for the KageShirei agent that provides tokio runtime functionality."
readme = "README.md"

[dependencies]
kageshirei-runtime = { path = "../../libs/kageshirei-runtime" }
kageshirei-communication-protocol = { path = "../../libs/kageshirei-communication-protocol" }
tokio = { version = "1", features = ["full"] }

[lints]
workspace = true