[package]
name = "srv-mod-terminal-emulator-commands"
version = "0.1.0"
edition = "2021"
categories = ["simulation"]
keywords = ["kageshirei", "server", "module", "terminal", "emulator"]
repository = "https://github.com/Kageshirei/KageShirei"
license-file = "../../LICENSE"
description = "A module for the KageShirei server that provides terminal emulator commands."
readme = "README.md"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
shellwords = "1.1.0"
tracing = "0.1.40"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.117" }
chrono = { version = "0.4.38", features = ["serde"] }
futures = "0.3.30"
tokio = { version = "1.40.0", features = ["full"] }
srv-mod-config = { path = "../srv-mod-config" }
kageshirei-communication-protocol = { path = "../../libs/kageshirei-communication-protocol" }
srv-mod-entity = { path = "../srv-mod-entity" }

[dev-dependencies]
serial_test = "3.1.1"

[lints]
workspace = true
