[package]
name = "srv-mod-handler-base"
version = "0.1.0"
edition = "2021"
categories = ["simulation"]
keywords = ["kageshirei", "server", "module", "handler", "base"]
repository = "https://github.com/Kageshirei/KageShirei"
license-file = "../../LICENSE"
description = "A module for the KageShirei server that provides base implementation for handlers."
readme = "README.md"

[dependencies]
tracing = "0.1.40"
serde = { version = "1.0.210", features = ["derive"] }
kageshirei-crypt = { path = "../../libs/kageshirei-crypt", features = [
    "sha3",
    "hex-encoding",
    "base32-encoding",
    "base64-encoding",
    "asymmetric-encryption",
    "server",
] }
srv-mod-config = { path = "../srv-mod-config" }
kageshirei-utils = { path = "../../libs/kageshirei-utils" }
axum = "0.7.7"
kageshirei-communication-protocol = { path = "../../libs/kageshirei-communication-protocol" }
mod-protocol-http = { path = "../mod-protocol-http" }
chrono = "0.4.38"
tokio = { version = "1.40.0", features = ["full"] }
serde_json = "1.0.128"
srv-mod-entity = { path = "../srv-mod-entity" }
humantime = "2.1.0"
kageshirei-format-json = { path = "../../libs/kageshirei-format-json" }

[dev-dependencies]
serial_test = "3.1.1"

[lints]
workspace = true