[package]
name = "srv-mod-handler-http"
version = "0.1.0"
edition = "2021"

[dependencies]
srv-mod-operator-api = { path = "../srv-mod-operator-api" }
srv-mod-config = { path = "../srv-mod-config" }
rs2-utils = { path = "../../libs/rs2-utils" }
serde = { version = "1.0.210", features = ["derive"] }
rs2-communication-protocol = { path = "../../libs/rs2-communication-protocol" }
tracing = "0.1.40"
axum = { version = "0.7.7", features = ["http2", "multipart", "macros"] }
axum-extra = { version = "0.9.4", features = ["typed-header"] }
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
tower = { version = "0.5.1" }
tower-http = { version = "0.6.1", features = [
    "catch-panic",
    "normalize-path",
    "sensitive-headers",
    "trace",
    "validate-request",
    "compression-full",
    "limit"
] }
tokio = { version = "1.40.0", features = ["full", "tracing", "test-util"] }
tokio-util = { version = "0.7.12", features = ["full"] }
mod-protocol-json = { path = "../mod-protocol-json" }
rs2-crypt = { path = "../../libs/rs2-crypt", features = [
    "sha3",
    "hex-encoding",
    "base32-encoding",
    "base64-encoding",
    "asymmetric-encryption",
] }
bytes = "1.7.2"
srv-mod-handler-base = { path = "../srv-mod-handler-base" }
srv-mod-entity = { path = "../srv-mod-entity" }
humantime = "2.1.0"

[dev-dependencies]
serde_json = "1.0.128"
serial_test = "3.1.1"