[package]
name = "rs2-agent"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
debug = false
debug-assertions = false
panic = "abort"
incremental = false

[dependencies]
wasmtime = { version = "21.0.1", default-features = false, features = ["runtime"] }
coffee-ldr = { path = "../libs/coffee" }

[features]
default = []
