[package]
name = "rs2-agent"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
debug = false
debug-assertions = false
panic = "abort"
incremental = false

[dependencies]
mod-coffee-core = { path = "../modules/mod-loader-coffee-core", optional = true }
mod-ntallocator = { path = "../modules/mod-ntallocator"}
libc-print = "0.1.23"

[features]
default = ["bof-loader"]
bof-loader = ["dep:mod-coffee-core"]
