[package]
name = "rs2-agent"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "z"
incremental = true
debug-assertions = false
lto = true

[dependencies]
coffee-ldr = { path = "../libs/coffee" }
