[config]
skip_core_tasks = true
default_to_workspace = false

[env]
TARGET = "x86_64-pc-windows-gnu"

[env.linux]
TARGET = "x86_64-unknown-linux-gnu"

[tasks.default]
clear = true
alias = "strip"

[tasks.build.linux]
clear = true
script_runner = "@shell"
script = '''
echo "$ cargo build --release --bin rs2-agent --target ${TARGET}"
cargo build --release --bin rs2-agent --target ${TARGET}
'''
env = { "RUSTFLAGS" = "-C panic=abort -C link-arg=-Wl,--nostdlib -C link-arg=-Wl,--gc-sections -C link-arg=-Wl,--strip-all" }

[tasks.build.windows]
clear = true
script_runner = "@shell"
script = '''
echo "$ cargo build --release --bin rs2-agent --target x86_64-pc-windows-msvc"
cargo build --release --bin rs2-agent --target x86_64-pc-windows-msvc
'''
env = { "RUSTFLAGS" = "-C panic=abort -C link-arg=/NODEFAULTLIB -C link-arg=/ENTRY:_start -C link-arg=/SUBSYSTEM:console -C link-arg=/MERGE:.rdata=.text -C link-arg=/MERGE:.data=.text -C link-arg=/OPT:REF,ICF" }

[tasks.strip.linux]
clear = true
script_runner = "@shell"
script = "strip -s ${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/x86_64-pc-windows-gnu/release/rs2-agent.exe"
dependencies = ["build"]
