# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
with_docs = true
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "diesel::sql_types::SqlType", "std::fmt::Debug", "Clone", "PartialEq"]

[migrations_directory]
dir = "migrations"
