[package]
name = "mod-std-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
kageshirei-communication-protocol = { path = "../../libs/kageshirei-communication-protocol" }
kageshirei-runtime = { path = "../../libs/kageshirei-runtime" }
serde = { version = "1.0", features = ["derive", "rc"] }