[package]
name = "mod-std-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
rs2-communication-protocol = { path = "../../libs/rs2-communication-protocol" }
rs2-runtime = { path = "../../libs/rs2-runtime" }
serde = { version = "1.0", features = ["derive", "rc"] }