[package]
name = "srv-mod-entity"
version = "0.1.0"
edition = "2021"
categories = ["simulation"]
keywords = ["kageshirei", "server", "module", "database", "entities"]
repository = "https://github.com/Kageshirei/KageShirei"
license-file = "../../LICENSE"
description = "A module for the KageShirei server that provides database entities."
readme = "README.md"

[dependencies]
sea-orm = { version = "1.0.1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-json"] }
serde = { version = "1.0.210", features = ["derive"] }
once_cell = "1.20.2"
cuid2 = "0.1.3"
kageshirei-communication-protocol = { path = "../../libs/kageshirei-communication-protocol", features = ["server"] }
humantime = "2.1.0"
serde_json = "1.0.128"

[lints]
workspace = true