name: Format check

on:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        # install Rust
      - name: install Rust nightly
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup toolchain install nightly
          rustup default nightly

      - name: Check formatting
        run: |
          . "$HOME/.cargo/env"
          cargo fmt --all --check
