name: Linting checks

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

        # install Rust
      - name: install Rust nightly
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup toolchain install nightly
          rustup default nightly

      - name: Check linting
        run: |
          . "$HOME/.cargo/env"
          cargo clippy --workspace --keep-going
