name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: kageshirei
          POSTGRES_USER: kageshirei
          POSTGRES_DB: kageshirei
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4

      # Install tauri dependencies
    - name: Tauri dependencies setup
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev

      # install node
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

      # install pnpm
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: latest
        run_install: false

      # install Rust nightly
    - name: install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        . "$HOME/.cargo/env"
        rustup default nightly
        rustup target add x86_64-pc-windows-gnu
        rustup target add x86_64-unknown-linux-gnu

      # Install the frontend dependencies
    - name: install frontend dependencies
      run: pnpm i -C command-and-control-gui

    - name: Migrate database
      run: |
        . "$HOME/.cargo/env"
        cargo install sea-orm-cli
        export DATABASE_URL=postgres://kageshirei:kageshirei@localhost:5432/kageshirei
        sea-orm-cli migrate fresh -d ./modules/srv-mod-migration/

    - name: Run tests
      run: |
        . "$HOME/.cargo/env"
        cargo test --verbose
